interface Env {
  XT_DB: D1Database;
  BALANCE_SYNC_QUEUE: Queue;
  TRADE_SYNC_QUEUE: Queue;
  TRADE_BACKFILL_SYNC_QUEUE: Queue;
  USER_INFO_SYNC_QUEUE: Queue;
  ENVIRONMENT?: string;
  XT_API_BASE_URL?: string;
  XT_AFFILIATE_USERS_PATH?: string;
  XT_AFFILIATE_USERS_URL?: string;
  XT_MCP_URL?: string;
  XT_SOURCE_KIND?: string;
  XT_HTTP_METHOD?: string;
  UID_SYNC_MAX_PAGES?: string;
  UID_SYNC_LIMIT?: string;
  BALANCE_SYNC_CHUNK_LIMIT?: string;
  TRADE_SYNC_CHUNK_LIMIT?: string;
  TRADE_BACKFILL_SYNC_DAY_LIMIT?: string;
  USER_INFO_SYNC_CHUNK_LIMIT?: string;
  XT_API_TOKEN?: string;
  ADMIN_IMPORT_TOKEN?: string;
}
